from __future__ import division

class ufo_exception(Exception):
    pass
